In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# load NN_dataset
filepath = "NN_dataset.csv"
NN_data = pd.read_csv(filepath)
NN_data.columns

Index(['Customer_ID', 'Num_CC', 'Dependents', 'Status_Checking_Acc',
       'Credit_History', 'Purposre_Credit_Taken', 'Savings_Acc',
       'Years_At_Present_Employment', 'Marital_Status_Gender',
       'Other_Debtors_Guarantors', 'Other_Inst_Plans ', 'Housing', 'Job',
       'Telephone', 'Foreign_Worker', 'Duration_binned',
       'Credit_amount_binned', 'Age_binned', 'Default_On_Payment'],
      dtype='object')

In [2]:
# set Customer_ID as index
NN_data.set_index('Customer_ID',inplace=True)

In [3]:
NN_data.dtypes

Num_CC                          int64
Dependents                      int64
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [4]:
NN_data['Num_CC'] = NN_data['Num_CC'].astype(str)
NN_data['Dependents'] = NN_data['Dependents'].astype(str)

In [5]:
NN_data.dtypes

Num_CC                         object
Dependents                     object
Status_Checking_Acc            object
Credit_History                 object
Purposre_Credit_Taken          object
Savings_Acc                    object
Years_At_Present_Employment    object
Marital_Status_Gender          object
Other_Debtors_Guarantors       object
Other_Inst_Plans               object
Housing                        object
Job                            object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [6]:
NN_data = NN_data.drop(columns=['Num_CC', 'Dependents', 'Status_Checking_Acc', 'Credit_History', 'Savings_Acc', 'Marital_Status_Gender', 'Other_Inst_Plans ', 'Job'])

In [7]:
NN_data.dtypes

Purposre_Credit_Taken          object
Years_At_Present_Employment    object
Other_Debtors_Guarantors       object
Housing                        object
Telephone                      object
Foreign_Worker                 object
Duration_binned                object
Credit_amount_binned           object
Age_binned                     object
Default_On_Payment              int64
dtype: object

In [8]:
NN_data.columns

Index(['Purposre_Credit_Taken', 'Years_At_Present_Employment',
       'Other_Debtors_Guarantors', 'Housing', 'Telephone', 'Foreign_Worker',
       'Duration_binned', 'Credit_amount_binned', 'Age_binned',
       'Default_On_Payment'],
      dtype='object')

In [9]:
NN_data.head()

Purposre_Credit_Taken Years_At_Present_Employment  \
Customer_ID                                                     
100001                        A43                         A75   
100002                        A43                         A73   
100003                        A46                         A74   
100004                        A42                         A74   
100005                        A40                         A73   

            Other_Debtors_Guarantors Housing Telephone Foreign_Worker  \
Customer_ID                                                             
100001                          A101    A152      A192           A201   
100002                          A101    A152      A191           A201   
100003                          A101    A152      A191           A201   
100004                          A103    A153      A191           A201   
100005                          A101    A153      A191           A201   

            Duration_binned Credit_amount_binned Age_binned  \
Customer_ID                                                   
100001                  B10                  B20        B35   
100002                  B14                  B22        B30   
100003                  B11                  B20        B33   
100004                  B13                  B23        B33   
100005                  B12                  B21        B33   

             Default_On_Payment  
Customer_ID                      
100001                        0  
100002                        0  
100003                        0  
100004                        0  
100005                        1

In [10]:
NN_data = pd.get_dummies(NN_data)

In [11]:
NN_data

Default_On_Payment  Purposre_Credit_Taken_A40  \
Customer_ID                                                  
100001                        0                          0   
100002                        0                          0   
100003                        0                          0   
100004                        0                          0   
100005                        1                          1   
...                         ...                        ...   
104996                        0                          0   
104997                        0                          0   
104998                        0                          0   
104999                        1                          0   
105000                        0                          0   

             Purposre_Credit_Taken_A41  Purposre_Credit_Taken_A410  \
Customer_ID                                                          
100001                               0                           0   
100002                               0                           0   
100003                               0                           0   
100004                               0                           0   
100005                               0                           0   
...                                ...                         ...   
104996                               0                           0   
104997                               1                           0   
104998                               0                           0   
104999                               0                           0   
105000                               1                           0   

             Purposre_Credit_Taken_A42  Purposre_Credit_Taken_A43  \
Customer_ID                                                         
100001                               0                          1   
100002                               0                          1   
100003                               0                          0   
100004                               1                          0   
100005                               0                          0   
...                                ...                        ...   
104996                               1                          0   
104997                               0                          0   
104998                               0                          1   
104999                               0                          1   
105000                               0                          0   

             Purposre_Credit_Taken_A44  Purposre_Credit_Taken_A45  \
Customer_ID                                                         
100001                               0                          0   
100002                               0                          0   
100003                               0                          0   
100004                               0                          0   
100005                               0                          0   
...                                ...                        ...   
104996                               0                          0   
104997                               0                          0   
104998                               0                          0   
104999                               0                          0   
105000                               0                          0   

             Purposre_Credit_Taken_A46  Purposre_Credit_Taken_A48  ...  \
Customer_ID                                                        ...   
100001                               0                          0  ...   
100002                               0                          0  ...   
100003                               1                          0  ...   
100004                               0                          0  ...   
100005                               0                 

In [12]:
data = NN_data.values
X = data[:, 1:77]
y = data[:, 0]

In [13]:
len(NN_data.columns)

46

In [14]:
X.shape, y.shape

((5000, 45), (5000,))

In [15]:
X[0]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1], dtype=int64)

In [16]:
# one-hot encode y (y data is already label encoded)
one_hot_y = to_categorical(y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [17]:
one_hot_y[0]

array([1., 0.], dtype=float32)

In [18]:
#split data to train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, one_hot_y, random_state=1)

In [19]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3750, 45), (1250, 45), (3750, 2), (1250, 2))

In [20]:
# create basic single hidden layer model to test (ignore future version warning)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=51, activation='relu', input_dim=45))
model.add(Dense(units=51, activation='relu'))
model.add(Dense(units=51, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 51)                2346      
_________________________________________________________________
dense_1 (Dense)              (None, 51)                2652      
_________________________________________________________________
dense_2 (Dense)              (None, 51)                2652      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 104       
Total params: 7,754
Trainable params: 7,754
Non-trainable params: 0
_________________________________________________________________


In [22]:
# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [23]:
# Fit the model to the training data
model.fit(
    X_train,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
3750/3750 - 1s - loss: 0.5909 - acc: 0.6960
Epoch 2/100
3750/3750 - 0s - loss: 0.5179 - acc: 0.7333
Epoch 3/100
3750/3750 - 0s - loss: 0.4666 - acc: 0.7773
Epoch 4/100
3750/3750 - 0s - loss: 0.4116 - acc: 0.8149
Epoch 5/100
3750/3750 - 0s - loss: 0.3362 - acc: 0.8536
Epoch 6/100
3750/3750 - 0s - loss: 0.2852 - acc: 0.8763
Epoch 7/100
3750/3750 - 0s - loss: 0.2352 - acc: 0.9037
Epoch 8/100
3750/3750 - 0s - loss: 0.1992 - acc: 0.9181
Epoch 9/100
3750/3750 - 0s - loss: 0.1807 - acc: 0.9221
Epoch 10/100
3750/3750 - 0s - loss: 0.1669 - acc: 0.9280
Epoch 11/100
3750/3750 - 0s - loss: 0.1533 - acc: 0.9331
Epoch 12/100
3750/3750 - 0s - loss: 0.1449 - acc: 0.9357
Epoch 13/100
3750/3750 - 0s - loss: 0.1409 - acc: 0.9349
Epoch 14/100
3750/3750 - 0s - loss: 0.1417 - acc: 0.9301
Epoch 15/100
3750/3750 - 0s - loss: 0.1333 - acc: 0.9389
Epoch 16/100
3750/3750 - 0s - loss: 0.1334 - acc: 0.9379
Epo

In [24]:
model_loss, model_accuracy = model.evaluate(
    X_test, y_test, verbose=2)
print(f"model - Loss: {model_loss}, Accuracy: {model_accuracy}")

1250/1250 - 0s - loss: 0.1025 - acc: 0.9344
model - Loss: 0.10253549745082856, Accuracy: 0.9344000220298767


In [25]:
from sklearn.metrics import classification_report

predictions = model.predict(X_test).round()
print(classification_report(y_test, predictions, target_names=["no-default", "default"]))

              precision    recall  f1-score   support

  no-default       0.95      0.96      0.95       901
     default       0.90      0.86      0.88       349

   micro avg       0.93      0.93      0.93      1250
   macro avg       0.92      0.91      0.92      1250
weighted avg       0.93      0.93      0.93      1250
 samples avg       0.93      0.93      0.93      1250

